version: '3.3'
services:
  postgres:
    image: mdillon/postgis:10
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
      PGDATA: /data
    volumes:
      - ~/db/nerveshub/postgres:/data
  nerves_hub_ca:
    image: nerveshub/nerves_hub_ca:v0.3.0
    entrypoint: ["/bin/bash"]
    command: ["/app/bin/nerves_hub_ca", "foreground"]
    ports:
      - "8443:8443"
    volumes:
      - type: bind
        source: ./test/fixtures/cfssl
        target: /etc/cfssl
