defaults: &defaults
  docker:
    - image: nerveshub/docker-build:latest
  working_directory: ~/repo

remote_docker: &remote_docker
  setup_remote_docker:
    version: 17.09.0-ce

docker_env: &docker_env
  run:
    name: Set docker env
    command: |
      if [ -z "$CIRCLE_TAG" ]; then
      BRANCH=$(git rev-parse --abbrev-ref HEAD)
        SHA=$(git rev-parse --short HEAD)
        TAG=$(echo "v.$BRANCH.$SHA" | sed 's/\//_/g')
      else
        TAG=$CIRCLE_TAG
      fi
      echo "export DOCKER_TAG=$TAG" >> $BASH_ENV
      echo "export DOCKER_IMAGE=nerveshub/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV

docker_build_release: &docker_build_release
  run:
    name: Build docker image
    command: |
      docker build \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -f rel/Dockerfile.build .

docker_push: &docker_push
  run: 
    name: Push docker image to dockerhub
    command: |
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      docker push \
        $DOCKER_IMAGE:$DOCKER_TAG

update_task: &update_task
  run: 
    name: Update ECS Task
    command: |
      TASK=$(rel/scripts/ecs-update-task.sh nerves_hub $DOCKER_IMAGE:$DOCKER_TAG)
      echo "export ECS_TASK=$TASK" >> $BASH_ENV

migrate: &migrate
  run:
    name: Run Migrations
    command: |
      rel/scripts/ecs-migrate.sh \
        nerves-hub \
        $ECS_TASK

deploy: &deploy
  run:
    name: Deploy to production
    command: |
      rel/scripts/ecs-deploy.sh \
        nerves-hub \
        nerves-hub \
        $ECS_TASK

version: 2
jobs:
  test:
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test
          DATABASE_URL: postgres://db:db@localhost:5432/db
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: db
          POSTGRES_DB: db
          POSTGRES_PASSWORD: db

    working_directory: ~/app

    steps:
      - checkout
      - run: wget https://github.com/fhunleth/fwup/releases/download/v1.2.0/fwup_1.2.0_amd64.deb
      - run: sudo dpkg -i ./fwup_1.2.0_amd64.deb
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Test
          command: mix coveralls.circle

      - run:
          name: Verify formatting
          command: mix format --check-formatted
  
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *remote_docker
      - <<: *docker_env
      - <<: *docker_build_release
      - <<: *docker_push
  
  deploy:
    <<: *defaults
    steps:
      - checkout
      - <<: *docker_env
      - <<: *update_task
      - <<: *migrate
      - <<: *deploy

workflows:
  version: 2
  pipeline:
      jobs:
        - test
        - build:
            context: org-global
            requires:
              - test
            filters:
              branches:
                only: master
        - deploy:
            context: org-global
            requires:
              - build
            filters:
              branches:
                only: master
